# This compose file uses two containers built from the NIST-ACE repository. Run the following commands prior
# to starting the docker compose deployment.
#
# docker build -t datamachines/nist-ace .
#
# cd lang/python/examples/analytics/opencv_object_detector && docker build -t ocv-ssd .


version: "2"
services:
  # ACE SERVICES
  ace:
    image: datamachines/nist-ace:demo
    restart: always
    command:
      - "tail" 
      - "-f" 
      - "/dev/null"

#  camera_stream:
#    image: datamachines/nist-ace:demo
#    restart: always
#    devices: 
#      - /dev/video0
#    ports:
#      - "8554:8554"
#    command:
#      - "python3"
#      - "-m"
#      - "ace"
#      - "serve"
#      - "rtsp"
#      - "--src=0" 
#      - "--endpoint=test"

  object_detector:
    image: ocv-ssd:demo
    restart: always
    ports:
      - "3000:3000"
    command:    
      - "--verbose"

  nats_server:
    image: nats:2.1.9
    restart: always
    ports: 
      - "4222:4222"

# DATABASE AND GRAFANA VISUALIZATION SERVICES
  influxdb:
    image: influxdb:1.7
    restart: always
    ports:
        - "8086:8086"
    volumes:
        - influxdb-storage:/var/lib/influxdb
    environment:
        INFLUXDB_DB: ace
  grafana:
    image: grafana/grafana
    restart: always
    ports:
        - "8088:3000"
    depends_on:
        - influxdb
    volumes:
        - grafana-storage:/var/lib/grafana
  



volumes:
  grafana-storage:
    external: true
  influxdb-storage:
    external: true
